### ISSUE TITLE
Building XorCurses fails

### ISSUE THREAD

**Issue by George1896** [jwm-art-net/XorCurses#1]
Hello,

Error output:

gcc -std=gnu99 -Wall -Wextra -DDATADIR=\"/usr/local/share/XorCurses/\" -DVERSION=\"0.2.2\"  actions.o  control_flow.o  data_file.o  exit.o  explode.o  fletcher.o  game_display.o  help.o  icons.o  info.o  level_menu.o  map.o  movelist.o  moves.o  options.o  player.o  play_xor.o  replay.o  scores.o  screen.o  splash.o  teleport.o  xorcurses.o -o xorcurses -lcurses
/usr/bin/ld: explode.o:(.bss+0x0): multiple definition of `player'; exit.o:(.bss+0x0): first defined here
[,...]
/usr/bin/ld: xorcurses.o:(.bss+0x0): multiple definition of `replay'; control_flow.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
However it does build when using clang-10 instead of gcc-10.

greetings
George1896

**Comment by jwm-art-net** [comment]
Thank you for the report. This is fixed in the latest commit.
